apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tests-kuberay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tests-kuberay
    app.kubernetes.io/part-of: ray
  name: tests-kuberay
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: tests-kuberay
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: tests-kuberay
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/ray/tests-kuberay@sha256:069bf108ec4debfa30507538d657a7b312299346866db16d6a30322fc5ef12be
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
