apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clients-kuberay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clients-kuberay
    app.kubernetes.io/part-of: ray
  name: clients-kuberay
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: clients-kuberay
status:
  loadBalancer: {}
