apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: odh-kuberay-operator-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odh-kuberay-operator-controller
    app.kubernetes.io/part-of: ray
  name: odh-kuberay-operator-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: odh-kuberay-operator-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: odh-kuberay-operator-controller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/ray/odh-kuberay-operator-controller@sha256:26288c40d7ea8e8b3e255d9f6271140ac2c08215fedce0eae3e55a9ecc2af993
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
