apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clients-kuberay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clients-kuberay
    app.kubernetes.io/part-of: ray
  name: clients-kuberayzhau
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: clients-kuberay
    weight: null
status: {}
