apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ray-operator-kuberay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ray-operator-kuberay
    app.kubernetes.io/part-of: ray
  name: ray-operator-kuberay
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ray-operator-kuberay
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ray-operator-kuberay
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/ray/ray-operator-kuberay@sha256:6138142d9aca06ee092e4c19f5c969a5df8d625fecbdc5a4026d0672828f35e8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
