apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ray-operator-kuberay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ray-operator-kuberay
    app.kubernetes.io/part-of: ray
  name: ray-operator-kuberay
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ray-operator-kuberay
status:
  loadBalancer: {}
