apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ray-operator-kuberay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ray-operator-kuberay
    app.kubernetes.io/part-of: ray
  name: ray-operator-kuberayh7fx
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ray-operator-kuberay
    weight: 100
status: {}
