apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: proto-kuberay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: proto-kuberay
    app.kubernetes.io/part-of: ray
  name: proto-kuberay
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: proto-kuberay
status:
  loadBalancer: {}
